### ISSUE TITLE
*** Hex viewer meta-issue

### ISSUE THREAD

**Issue by luelista** [luelista/pre_workbench#12]
* [x] re-implement "Data Inspector" in HexView #4 
* [x] Entropy detection #1 
* [ ] histogram (1, 2, 4 byte blocks)
* [x] simple range annotation
* [x] create FormatInfo fields from context menu
* [ ] faster implementation of RangeList (intervaltree?)

**Comment by luelista** [comment]
rest are not really hexview issues
